/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sc2008_lab;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;

public class App {
    // Name: Zhu Zhanyan
    // Group: SCSD
    // IP Address: <IP>
    private static final byte[] send = "ZhuZhanyan, SCSD, 10.96.188.54".getBytes();

    public static void main(String[] args) {
        // open udp on any port socket to make quote of the day requests
        try (DatagramSocket socket = new DatagramSocket()) {
            try {
                DatagramPacket outPacket = new DatagramPacket(send, send.length,
                        InetAddress.getByName("10.96.189.98"), 17);
                socket.send(outPacket);

                DatagramPacket inPacket = new DatagramPacket(new byte[1024], 1024);
                socket.receive(inPacket);

                String quote = new String(inPacket.getData());
                System.out.println("Quote: " + quote);
            } catch (IOException e) {
                System.out.println("IO exception reading or writing socket");
                e.printStackTrace();
            }

        } catch (SocketException e) {
            throw new RuntimeException(e);
        }
    }
}
